### ISSUE TITLE
Lack of references in bulletproofs.pdf

### ISSUE THREAD

**Issue by Kantemir** [b-g-goodell/research-lab#44]
There are no references in bulletproofs.pdf, while the most part of the file is about some changes of the protocol described in the other article.
I suppose that was "Bulletproofs: Short Proofs for Confidential Transactions and More" by Bunz et al, but in this case there is a question about notation.
For example:

1. > we observe that the curve points in Equation (10)

    **There are not curve points in (10).** It's even not an equation, anyway.
2. There are no G_i or H_i in the given article but they are used in bulletproofs.pdf.

**Comment by SarangNoether** [comment]
The technical note you describe refers to an older version of the Bulletproofs paper, before many of our optimizations were added to it. You should consider this technical note obsolete.

**Comment by SarangNoether** [comment]
The most recent version of the Bulletproofs paper on IACR is the best resource for the algorithms themselves.
